services:
  - type: web
    name: codestrology
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: base64:gdFnbsWlejN18VFvzzfyAuBLancUk3/4ltdhusneCVI=
      - key: APP_DEBUG
        value: false
      - key: SESSION_DRIVER
        value: file
